### ISSUE TITLE
No User table found

### ISSUE THREAD

**Issue by HiteshKhatri02** [google/santa-tracker-android#8]
com.google.android.apps.santatracker.debug E/UncaughtException: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.apps.santatracker.debug/com.google.android.apps.santatracker.presentquest.MapsActivity}: android.database.sqlite.SQLiteException: no such table: USER (code 1): , while compiling: SELECT * FROM USER
                                                                                               #################################################################
                                                                                               Error Code : 1 (SQLITE_ERROR)
                                                                                               Caused By : SQL(query) error or missing database.
                                                                                               	(no such table: USER (code 1): , while compiling: SELECT * FROM USER)
                                                                                               #################################################################
                                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
                                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
                                                                                                   at android.app.ActivityThread.access$1100(ActivityThread.java:229)
                                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                                   at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                                                Caused by: android.database.sqlite.SQLiteException: no such table: USER (code 1): , while compiling: SELECT * FROM USER
                                                                                               #################################################################
                                                                                               Error Code : 1 (SQLITE_ERROR)
                                                                                               Caused By : SQL(query) error or missing database.
                                                                                               	(no such table: USER (code 1): , while compiling: SELECT * FROM USER)
                                                                                               #################################################################
                                                                                                   at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                                   at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1058)
                                                                                                   at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:623)
                                                                                                   at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                                                   at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
                                                                                                   at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                                                   at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                                                   at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1471)
                                                                                                   at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1318)
                                                                                                   at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1189)
                                                                                                   at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1395)
                                                                                                   at com.orm.SugarRecord.find(SugarRecord.java:192)
                                                                                                   at com.orm.SugarRecord.listAll(SugarRecord.java:94)
                                                                                                   at com.google.android.apps.santatracker.presentquest.model.User.get(User.java:93)
                                                                                                   at com.google.android.apps.santatracker.presentquest.MapsActivity.onCreate(MapsActivity.java:285)
                                                                                                   at android.app.Activity.performCreate(Activity.java:6904)
                                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)

**Comment by samtstern** [comment]
@HiteshKhatri02 are you using Instant Run?  I've seen this issue before when using Instant Run.  In my case I had to install the app once without instant run enabled and then I was able to use instant run in the future.

**Comment by HiteshKhatri02** [comment]
@samtstern Thanks, Now it's working fine.
